config/routes.rb
Layprophet::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#cover"
  get "about" => "pages#about" #create about_path
  get "pieces" => "pages#pieces"
  get "cover" => "pages#cover"
  get "index" => "pins#index"
  get "article1" => "pages#article1"
  get "rankings" => "pages#rankings"
  get "dranpage" => "pages#dranpage"
  get "varini1" => "pages#varini1"
  get "ox1" => "pages#ox1"
  get "stikman" => "pages#stikman"
  get "bumblebee" => "pages#bumblebee"
  get "reka" => "pages#reka"
  get "ludo" => "pages#ludo"
  get "herakut" => "pages#herakut"
  get "claudioethos" => "pages#claudioethos"
  get "dface" => "pages#dface"
  get "pandilla" => "pages#pandilla"
  get "mobstr" => "pages#mobstr"
  get "daleast" => "pages#daleast"
  get "clarionalley" => "pages#clarionalley"
  get "socialpiece" => "pages#socialpiece"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates :image, presence: true
 	validates :title_Of_Piece, presence: true
 	validates :brand, presence: true
	validates :comment, presence: true

	
	validates :title_Of_Piece, length: { minimum: 1 }
 	validates :title_Of_Piece, length: { maximum: 255 }
	validates :brand, length: { minimum: 1 }
  	validates :brand, length: { maximum: 255 }
  	validates :comment, length: { minimum: 1 }
  	validates :comment, length: { maximum: 255 }

  	#validates :password, length: { in: 6..40 }


	def self.search(search)
		
	  if search	
      	where('comment ILIKE ? OR "brand" ILIKE ? OR "title_Of_Piece" ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
	  else
	    scoped
	  end

	end
	has_attached_file :image, :styles => { :medium => "700x700>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true #uniqueness? should we?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

	 def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) << :name
	   devise_parameter_sanitizer.for(:account_update) << :name
	 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def pieces
  end

  def cover
  end

  def article1
  end

  def dranpage
  end
  
  def rankings
  end

  def varini1
  end

  def ox1
  end

  def stikman
  end

  def bumblebeelovesyou
  end

  def reka
  end

  def ludo
  end

  def herakut
  end

  def claudioethos
  end

  def dface
  end

  def pandilla
  end

  def mobstr
  end

  def daleast
  end
  
  


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  helper_method :sort_column, :sort_direction

  def index
    @pins = Pin.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 50, :page => params[:page])
    #@pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    #@pin = current_user.pins.build(pin_params)
    #if @pin.save
     # redirect_to @pin, notice: 'Pin was successfully created.'
    #else
     # render action: 'new'
    #end


    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin }
        #format.html { redirect_to @pin, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
   # if @pin.update(pin_params)
    #  redirect_to @pin, notice: 'Pin was successfully updated.'
   # else
    #  render action: 'edit'
    #end


    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this post" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:image, :title_Of_Piece, :brand, :comment)
    end

    def sort_column
      params[:sort] || "comment" || "brand" || "title_Of_Piece"
    end
  
    def sort_direction
      params[:direction] || "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!--<nav class="navbar navbar-default" role="navigation">-->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "HUNTER PLASTERWALL", cover_path, class: "navbar-brand" %>
      <!--<h5>write a review about some clothes, upload an art piece, or something interesting</h5>--> 
   </div>
    
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%if !user_signed_in? %>
        <li><%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-default btn-xs" %></li>
        <li><%= link_to "PIECES", pieces_path %></li>
        <li><%= link_to "SOCIAL", index_path %></li>
        <li><%= link_to "RANKINGS", rankings_path %></li>
        <li><%= link_to "ABOUT", about_path %></li>
        <% else %>
        <li><%= link_to "PIECES", pieces_path %></li>
        <li><%= link_to "SOCIAL", index_path %></li>
        <li><%= link_to "RANKINGS", rankings_path %></li>
        <li><%= link_to "ABOUT", about_path %></li>
        <% end %>
        <%if user_signed_in? %>
            <li><%= link_to '+ADD', new_pin_path %></li>
            <li><%= link_to "SETTINGS", edit_user_registration_path %></li>
            <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "SIGN IN", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Hunter Plasterwall</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>



</body>
</html>

app/views/pages/about.html.erb
<b><h3>about</h3></b></br>

<h1>"You're Worth Every Penny"</h1>

<h2>Clothes <small>canvas</small></h2>
  <h2>Spray Paint <small>street legitimacy</small></h2>
  <h2>Internet <small>Use the Social page, we have an online wall!</small></h2>
  <h2>Activism <small>We are the rich and the poor, the young and the old. We are everlasting life in fashion. <small></h2>
	
</br>

<address><h4>
  <strong>Concern, question or feedback? Let us know: </strong><br>
  <a href="mailto:#">hplasterwall@gmail.com</a></h4>
</address>
</br>


<div class="action pull-right">
<!-- Button trigger modal -->
<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  +
</button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">It's actually for underpriveledged kids</h3>
      </div>
      <div class="modal-body">
      	<h4>
        This concept was birthed out of wanting to help underpriveledged kids in my local community, my neighborhoods, my city, my state, country, and my world.  I want a brand that everyone can wear, is proud to wear while looking fantastic.  As income inequality joins forces with high fashion brands.. let's just call this a people's union in response.  Salvador Ferragamo, Yves Saint Laurent, Pigalle, Lanvin, Dsquared, Comme Des Garcon you people are good, but we aren't stupid and we are coming for you.  We can talk about who runs the world, but then we would have to talk about a French Revolution, an Arab Spring, a Kiev Riot, Korean Democracy, a Haitian Nation, etc. Oh yeah, also, if you need to make money by copying/selling Jueles Mayflower branded clothes, then go ahead, just don't get too rich with out us or else at that point we'll sue.  Other than that, let's make it look good.
    	</br>
    	</br>
        <div class="action pull-left">
      		<i><h6>-Plasterwall</h6></i>
      	</div>
    	</h4>	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div></br>

app/views/pages/article1.html.erb
</br>
<div class="panel panel-default">
	<div class="action center">
		</br>

		<div class="action center">
		<h1>Kidult, so disrespectful, but it looks so good</h1>
		<h4>March 18, 2014</h4>
		<h4>by Hunter Plasterwall and Team</h4></div>

		 <img src="http://recklessanimals.files.wordpress.com/2013/06/kidult-hits-maison-martin-margiela-in-brussels-1.jpg"  style="max-width:100%" alt="The Mayflower" height="1160" width="1000"/>

		<div class="action center">

		<i><p>"The cities are the theater of a battle for space, a battle in which I try to expose my vision of the world, and destroy theirs. My extinguishers, paint and spray cans are my weapons of mass destruction. They may have all the money in the world; they will never win in the streets because we are the streets!

		The army is growing and the struggle is global. 
 		I am not the one who declared the war, I just responded to defend my vision of what graffiti and society should be, free." 			-Kidult</p></i>

 		</div>

 		 <img src="http://i762.photobucket.com/albums/xx270/akimn89/kidult1_zps4983e8d3.jpg"  style="max-width:100%" alt="The Mayflower" height="1160" width="1000"/>

 		</br>
 		<div class="action">

	 		<p>Kidult to me is an inspiration.  Fearlessness, strength, and passion come to mind from Kidult's works.  Although one could claim madness, I find it hard to disagree with everything that Kidult stands for. 
	 		</br>
	 		Kidult is freeing someone's mind.  Personally, I am not going to endorse painting on store fronts, but I do believe that we need less fear in our lives, more strength, and passion.  Life without salt, pepper, spice, is bland. But everything I have written is up to individuals to determine for themselves.
			</br>
			Here at Hunter Plasterwall, we are inspired by passion.  Thanks Kidult, stay safe, we enjoy your work! </p>
		</div>

		<img src="http://www.perrerarte.cl/wp/wp-content/uploads/2012/11/Kidult-6.gif"  style="max-width:100%" alt="The Mayflower" height="1160" width="1000"/>

	
		
	</div>
</div>

		</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>

app/views/pages/bumblebee.html.erb
</br>
<div class="panel panel-default">
	<div class="action center">
		</br>

		<div class="action center">
		<h1>Bumblebee Sweetens Life (Artist: Bumblebeelovesyou)</h1>
		<h4>March 21, 2014</h4></br>

		 <img src="http://arrestedmotion.com/wp-content/uploads/2014/01/mutualfeeling.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		 <img src="http://payload242.cargocollective.com/1/0/633/7141694/studio_1000.jpg"  style="max-width:100%" alt="OX" height="1160" width="1000"/></br></br>

		<div class="action pull-left">

		<p>
		The documentation of youth homelessness via paintings is… let’s use the word precious.  That was a focus that Bumblebeelovesyou had.  When I read youth homelessness, my soul became quiet.  I did not know what to say.  It’s not that I have been homeless or wish to be homeless, but I have seen youth homelessness in America.  I am not so sure about other countries, but in America, there is youth homelessness. </br></br>
		Together, youth homelessness and art, I find, as one of the cooler things I have heard of.  I am happy I came across bumblebee.  Bumblebee sweetens life.  I really like life when it is poetic.  To me, it (Youth homelessness and Street art) sounds like poetry.</br></br>  


		</p>

 		</div>

 		 <img src="https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-prn1/t31/c0.138.851.315/p851x315/1622399_619164134823079_1221656244_o.jpg"  style="max-width:100%" alt="Ox" height="1160" width="1000"/>

 		</br></br>

 		<img src="http://cdn.respect-mag.com/wp-content/uploads/2013/03/Screen-Shot-2013-03-28-at-1.50.41-PM.png"  style="max-width:100%" alt="Ox" height="1160" width="1000"/>

 		</br></br>

		<img src="http://3.bp.blogspot.com/-WBAqAUFTSR0/TnTfuNhQPVI/AAAAAAAAWa4/AhPMmWa55Fg/s1600/DSC02272.JPG"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		<img src="http://3.bp.blogspot.com/-H2mD2K1MV-8/UhVOuEwW7LI/AAAAAAAABSo/8RY-dNQV_7Y/s1600/9563918849_6e3346c95d_b.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>


		<img src="http://arrestedmotion.com/wp-content/uploads/2013/03/title-Walk-the-Dog-artst-Bumblebeelovesyou-sfw-am.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>
		
		<img src="http://www.lataco.com/taco/wp-content/uploads/BeeYourself_9_of_25-800x531.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>


		
	</div>
</div>

		</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>

app/views/pages/daleast.html.erb
</br>
<div class="panel panel-default">
	<!--<div class="action center">-->
		</br>

		<div class="action center">
		<h1>DALeast, Mr. James, & Richard</h1>
		<h4>March 31, 2014</h4></br>

		 <img src="http://www.brooklynstreetart.com/theblog/wp-content/uploads/2013/11/brooklyn-street-art-dal-east-spencer-elzey-london-10-13-web.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		 <img src="http://www.dailyartfixx.com/wp-content/uploads/2011/08/redeer-bratislava-slovakia-2011-DAL.jpg"  style="max-width:100%" alt="OX" height="1160" width="1000"/></br></br>

		 </div>

		<div class="action pull-left">

		<p>
		Based on some of the art that we've seen online, on this site, and other places; DALeast works are pretty good.  Loving something that looks good is so easy.  </br></br>

		Alright, let's get this out of the way, let's talk Lebron James for a second.  The dude is a well proportioned man while being 2 to 3 times larger and maybe 2 to 3 times faster (Bear with me) than the average man.  That would make him 6 times or 9 times faster than the average man because we were counting in Lebron measurements not the average man.  I don't know, but that paints a general picture I think.   The guy was the last superstar drafted out of high school, he was anointed as the chosen one by Nike, and he has topped it off with two NBA Championship rings.  His age is not all that bad either, especially if we take into perspective Kobe Bryant's age and the career Kobe has had so far.  For the ladies who don't care, just take it as an info session, and for the guys, you can do the same.  :)  </br></br>
		Anyways, I personally dislike Lebron James.  His game is pretty good, decent entertainment, he get's the job done, he does not look that bad besides some early balding.  But then again, I wonder how many people in America hate Richard Sherman, a non-mediocre cornerback for the Seattle Seahawks.  I like Richard Sherman.   But that's probably because I know his background and how hard he worked to get where he is.  I am sure that Lebron works more at his game than I think, but maybe he's too tired to show any of that.  Or maybe he just does not know how to appeal to all fans.  But can anyone capture an entire audience?  </br></br>
		Honestly, I like Richard Sherman 100 times more than Lebron James. Go Seattle. </br></br></br></br>



		</p>

 		</div>

 		<div class="action center">

 		<img src="http://payload28.cargocollective.com/1/0/633/2866091/DALeast-The%20Williams%20Brothers%201-%20Cape%20Town-South%20Africa-%202012.2%20hq_1000.jpg"  style="max-width:100%" alt="Ox" height="1160" width="1000"/>

 		</br></br>

		<img src="http://api.ning.com/files/b11Oq4bm9ffV3d*TnNEt2bNjQPU1OMywfWzZndZ3x73sCzfkPq-DiXc94dDNE1OQS*RALERBFGgsOIRT8ifQoV3-CDYmvkXz/DAL1.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		<img src="http://www.lifelounge.com.au/resources/imgdetail/020312041203_dal-detail.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>


		<img src="http://payload147.cargocollective.com/1/0/633/5255863/DALeast--Abscission--%20Honolulu-Hawaii-2013photo-Brandon%20Shigeta_1000.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>
		
		<img src="http://4.bp.blogspot.com/-_cFPbcDas1s/T0i5c9Bi2kI/AAAAAAAALDo/VthzWh4YSew/s1600/DALeast-'Deer+Park-D',cape+town,south+africa,2012.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>

		<img src="http://vrais.fatcap.org:8081/uploads/msc/2013-06-22/lv_82cb347cc7c3dd71f247e2c388f2564625467459.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>
		
		<img src="http://vrais.fatcap.org:8081/uploads/msc/2013-06-22/lv_d31c011b6b54a3ff9e3a95e4ef2438f8d1dbe700.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>

		<img src="http://s1.ibtimes.com/sites/www.ibtimes.com/files/styles/v2_article_large/public/2013/10/28/dal.png"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>

		
		<h3>The Chainsmokers - #Selfie</h3></br>
		
		<iframe width="700" height="400" src="http://www.youtube.com/embed/kdemFfbS5H0" style="max-width:100%"      frameborder="0"></iframe>
		
	</div>
</div>

		</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>

app/views/pages/dranpage.html.erb
</br>
<div class="panel panel-default">
	<div class="action center"></br>
		<h4>March 16, 2014</h4>

		<img src="http://api.ning.com/files/tVmzSqOjQqN1PYVQ05ciLZfq6*mty5-0*HCTljgf7fAQZPh9CKzsd9tT9bh2q37LnNsE5o8pnGVjp*PsN7XYlrmG4n0ex1ZC/dranstreetart7.jpeg" alt="Dran Van Gogh Selfie" height="290" width="250"/></br>

		</br>

		<img src="http://arrestedmotion.com/wp-content/uploads/2010/11/Dran_I_Have_Chalks-450x609.jpg" alt="Dran I have chalks" height="290" width="250"/></br>


		</br>

		<img src="http://houhouhaha.fr/wp-content/uploads/2012/04/d20.jpg" alt="Dran 3d Pic 1" height="290" width="250"/></br>

		</br>

		<img src="http://streetartlondon.co.uk/artists/files/2011/01/Dran-Street-Artist.jpg" alt="Dran gallery boxes"height="290" width="250"/></br>

	</div>
</div>

	</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>

app/views/pages/hera.html.erb
</br>
<div class="panel panel-default">
	<div class="action center">
		</br>

		<div class="action center">
		<h1>Hot Topic: Herakut</h1>
		<h4>March 24, 2014</h4></br>

		 <img src="http://arrestedmotion.com/wp-content/uploads/2009/05/img_1649_spec_exhibit.jpg
"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		 <img src="http://thedolab.com/wp-content/uploads/2011/11/IMG_2733.jpg
"  style="max-width:100%" alt="OX" height="1160" width="1000"/></br></br>

		<div class="action pull-left">

		<p>
		This duo has been at it since 2004.  I really like this combination.  There is some good flow between their styles.  I love how it is feminine and sensual yet full of meaningful color.  It is sexy.    </br></br>

		The last picture posted up on here, I would put that on a t shirt.
	</br></br> 
	
		



		</p>

 		</div>

 	
 		<img src="http://www.streetartbln.com/wp-content/uploads/2013/10/Herakut_Monkey_Mural_Street_Art_Berlin_1588_Blog.jpg"  style="max-width:100%" alt="Ox" height="1160" width="1000"/>

 		</br></br>

		<img src="http://spaceelephant.com/wp-content/uploads/featured_image/herakut_street_art_91.jpeg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>

		<img src="http://www.streetartutopia.com/wp-content/uploads/2011/09/street_art_herakut_4.jpeg"  style="max-width:100%" alt="ox" height="1160" width="1000"/></br></br>


		<img src="http://api.ning.com/files/vgkdCMlQvIgxDbPFLk5Jb*9gNlSRjJIpIujvqvSqahsT7coyumGWZSN2zMT9fq3aGm6G3etzEXI3PZQi07Q5EmjXkRJXmaMG/HappyDoubtDayHerakut7.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>
		
		<img src="http://thesuiteworld.com/wp-content/uploads/2011/06/HERAKUT-telaviv-tel-aviv-street-art-graffiti-israel-cat.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>

		<img src="http://www.streetartutopia.com/wp-content/uploads/2011/04/street_art_herakut_5.jpeg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>
		
		<img src="http://artsandjunk.files.wordpress.com/2011/04/herakut2.jpg"  style="max-width:100%" alt="ox" height="1160" width="1000"/>	</br></br>


		<h3>Serebro - Mi Mi Mi </h3></br>

		<iframe width="700" height="400" src="http://www.youtube.com/embed/nlt5Wa13fFU" style="max-width:100%"      frameborder="0"></iframe>
		
	</div>
</div>

		</br>
	</br>
	</br>
	</br>
	</br>
	</br>
	</br>

app/views/pins/_pins.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<!--<table class="table table-hover">-->
<!--<div class="panel-body">-->

<!--"created_at", "Date"-->

<!--<div class="panel panel-primary">primary was default before-->
<div id="pins" class="transitions-enabled">
  <!--<div class="panel panel-default">-->
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <div class="actions center">
          <dl>
            
            <%= image_tag pin.image.url(:medium) %>
              <dt><h3><%= link_to pin.title_Of_Piece, pin_path(pin) %></h3></dt>
              <dt><%= pin.brand %></dt>
              <dd><%= pin.comment %></dd>
              <br>
              <dd>by <%= pin.user.name if pin.user %></dd>
              <dt><h6><%= pin.created_at.strftime("%b %d, %Y") %></h6></dt></br>

                <% if current_user && (pin.user == current_user) %>
                  <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Delete', pin, class: "btn btn-primary btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
                
          </dl>
        </div>
      </div>
    <% end %>
  </div>
<!--</div>-->

<!--</div>-->

<div class="actions center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

    <!--<%= will_paginate @posts %>-->

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<!--<%= render 'pages/home' unless user_signed_in? %>-->
  
   </br>
    <%= form_tag pins_path, :method => 'get' , :id => "pins_search" do %>
      
      <div class="actions pull-right">
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "SEARCH", :name => nil, class: "btn btn-default btn-xs" %>
        </p>
      </div>

        <%= sortable "created_at", "By Date" %></br>
        </div>

      <div id="pins">
          <%= render 'pins' %>
      </div>  

  <% end %>

app/views/pins/show.html.erb
</br>
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url() %>
				<p>
				 <h2><%= @pin.title_Of_Piece %></h2>
				</p>

				<p>
				  <h4><%= @pin.brand %></h4>
				</p>

				<p>
				  <%= @pin.comment %>
				</p>
			
				<p><h5>
					by <%= @pin.user.name if @pin.user %></h5>
				</p>

				<p>
					<h6><%= @pin.created_at.strftime("%b %d, %Y") %></h6>
				</p>
				</br>

				<% if current_user && (@pin.user == current_user) %>
					<%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-primary btn-xs" %>
					<%= link_to 'Delete', @pin, class: "btn btn-primary btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</div>	
		</div>
	</div>
</div>
<!--</div>-->